<?php

function countries_rest_api_theme() {
  return [
    'country_list' => [
      'variables' => [
        'characteristics' => NULL,
      ],
    ],
    'country_details_list' => [
      'variables' => [
        'names' => NULL,
        'independent' => NULL,
        'currency' => NULL,
        'capital' => NULL,
        'region' => NULL,
        'subregion' => NULL,
        'languages' => NULL,
        'maps' => NULL,
        'timezone' => NULL,
        'continent' => NULL
      ],
    ],
  ];
}
